/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PairRouteImport } from './routes/pair'
import { Route as OperatorRouteImport } from './routes/operator'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KioskRouteImport } from './routes/kiosk'
import { Route as DisplayRouteImport } from './routes/display'
import { Route as CustomerRouteImport } from './routes/customer'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTicketsRouteImport } from './routes/app.tickets'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppServicesRouteImport } from './routes/app.services'
import { Route as AppQueuesRouteImport } from './routes/app.queues'
import { Route as AppPagesRouteImport } from './routes/app.pages'
import { Route as AppOrdersRouteImport } from './routes/app.orders'
import { Route as AppMenusRouteImport } from './routes/app.menus'
import { Route as AppKioskEditorRouteImport } from './routes/app.kioskEditor'
import { Route as AppEmployeesRouteImport } from './routes/app.employees'
import { Route as AppDevicesRouteImport } from './routes/app.devices'
import { Route as AppCountersRouteImport } from './routes/app.counters'
import { Route as AppCompaniesRouteImport } from './routes/app.companies'
import { Route as AppBranchesRouteImport } from './routes/app.branches'
import { Route as AppAuditRouteImport } from './routes/app.audit'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'

const PairRoute = PairRouteImport.update({
  id: '/pair',
  path: '/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorRoute = OperatorRouteImport.update({
  id: '/operator',
  path: '/operator',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KioskRoute = KioskRouteImport.update({
  id: '/kiosk',
  path: '/kiosk',
  getParentRoute: () => rootRouteImport,
} as any)
const DisplayRoute = DisplayRouteImport.update({
  id: '/display',
  path: '/display',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRoute = CustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTicketsRoute = AppTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesRoute = AppServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AppRoute,
} as any)
const AppQueuesRoute = AppQueuesRouteImport.update({
  id: '/queues',
  path: '/queues',
  getParentRoute: () => AppRoute,
} as any)
const AppPagesRoute = AppPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppMenusRoute = AppMenusRouteImport.update({
  id: '/menus',
  path: '/menus',
  getParentRoute: () => AppRoute,
} as any)
const AppKioskEditorRoute = AppKioskEditorRouteImport.update({
  id: '/kioskEditor',
  path: '/kioskEditor',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesRoute = AppEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AppRoute,
} as any)
const AppDevicesRoute = AppDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AppRoute,
} as any)
const AppCountersRoute = AppCountersRouteImport.update({
  id: '/counters',
  path: '/counters',
  getParentRoute: () => AppRoute,
} as any)
const AppCompaniesRoute = AppCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AppRoute,
} as any)
const AppBranchesRoute = AppBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/customer': typeof CustomerRoute
  '/display': typeof DisplayRoute
  '/kiosk': typeof KioskRoute
  '/login': typeof LoginRoute
  '/operator': typeof OperatorRoute
  '/pair': typeof PairRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/branches': typeof AppBranchesRoute
  '/app/companies': typeof AppCompaniesRoute
  '/app/counters': typeof AppCountersRoute
  '/app/devices': typeof AppDevicesRoute
  '/app/employees': typeof AppEmployeesRoute
  '/app/kioskEditor': typeof AppKioskEditorRoute
  '/app/menus': typeof AppMenusRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/pages': typeof AppPagesRoute
  '/app/queues': typeof AppQueuesRoute
  '/app/services': typeof AppServicesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tickets': typeof AppTicketsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customer': typeof CustomerRoute
  '/display': typeof DisplayRoute
  '/kiosk': typeof KioskRoute
  '/login': typeof LoginRoute
  '/operator': typeof OperatorRoute
  '/pair': typeof PairRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/branches': typeof AppBranchesRoute
  '/app/companies': typeof AppCompaniesRoute
  '/app/counters': typeof AppCountersRoute
  '/app/devices': typeof AppDevicesRoute
  '/app/employees': typeof AppEmployeesRoute
  '/app/kioskEditor': typeof AppKioskEditorRoute
  '/app/menus': typeof AppMenusRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/pages': typeof AppPagesRoute
  '/app/queues': typeof AppQueuesRoute
  '/app/services': typeof AppServicesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tickets': typeof AppTicketsRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/customer': typeof CustomerRoute
  '/display': typeof DisplayRoute
  '/kiosk': typeof KioskRoute
  '/login': typeof LoginRoute
  '/operator': typeof OperatorRoute
  '/pair': typeof PairRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/branches': typeof AppBranchesRoute
  '/app/companies': typeof AppCompaniesRoute
  '/app/counters': typeof AppCountersRoute
  '/app/devices': typeof AppDevicesRoute
  '/app/employees': typeof AppEmployeesRoute
  '/app/kioskEditor': typeof AppKioskEditorRoute
  '/app/menus': typeof AppMenusRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/pages': typeof AppPagesRoute
  '/app/queues': typeof AppQueuesRoute
  '/app/services': typeof AppServicesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tickets': typeof AppTicketsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/customer'
    | '/display'
    | '/kiosk'
    | '/login'
    | '/operator'
    | '/pair'
    | '/app/analytics'
    | '/app/audit'
    | '/app/branches'
    | '/app/companies'
    | '/app/counters'
    | '/app/devices'
    | '/app/employees'
    | '/app/kioskEditor'
    | '/app/menus'
    | '/app/orders'
    | '/app/pages'
    | '/app/queues'
    | '/app/services'
    | '/app/settings'
    | '/app/tickets'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customer'
    | '/display'
    | '/kiosk'
    | '/login'
    | '/operator'
    | '/pair'
    | '/app/analytics'
    | '/app/audit'
    | '/app/branches'
    | '/app/companies'
    | '/app/counters'
    | '/app/devices'
    | '/app/employees'
    | '/app/kioskEditor'
    | '/app/menus'
    | '/app/orders'
    | '/app/pages'
    | '/app/queues'
    | '/app/services'
    | '/app/settings'
    | '/app/tickets'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/customer'
    | '/display'
    | '/kiosk'
    | '/login'
    | '/operator'
    | '/pair'
    | '/app/analytics'
    | '/app/audit'
    | '/app/branches'
    | '/app/companies'
    | '/app/counters'
    | '/app/devices'
    | '/app/employees'
    | '/app/kioskEditor'
    | '/app/menus'
    | '/app/orders'
    | '/app/pages'
    | '/app/queues'
    | '/app/services'
    | '/app/settings'
    | '/app/tickets'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CustomerRoute: typeof CustomerRoute
  DisplayRoute: typeof DisplayRoute
  KioskRoute: typeof KioskRoute
  LoginRoute: typeof LoginRoute
  OperatorRoute: typeof OperatorRoute
  PairRoute: typeof PairRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pair': {
      id: '/pair'
      path: '/pair'
      fullPath: '/pair'
      preLoaderRoute: typeof PairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator': {
      id: '/operator'
      path: '/operator'
      fullPath: '/operator'
      preLoaderRoute: typeof OperatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kiosk': {
      id: '/kiosk'
      path: '/kiosk'
      fullPath: '/kiosk'
      preLoaderRoute: typeof KioskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/display': {
      id: '/display'
      path: '/display'
      fullPath: '/display'
      preLoaderRoute: typeof DisplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tickets': {
      id: '/app/tickets'
      path: '/tickets'
      fullPath: '/app/tickets'
      preLoaderRoute: typeof AppTicketsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/services': {
      id: '/app/services'
      path: '/services'
      fullPath: '/app/services'
      preLoaderRoute: typeof AppServicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/queues': {
      id: '/app/queues'
      path: '/queues'
      fullPath: '/app/queues'
      preLoaderRoute: typeof AppQueuesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pages': {
      id: '/app/pages'
      path: '/pages'
      fullPath: '/app/pages'
      preLoaderRoute: typeof AppPagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/orders': {
      id: '/app/orders'
      path: '/orders'
      fullPath: '/app/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/menus': {
      id: '/app/menus'
      path: '/menus'
      fullPath: '/app/menus'
      preLoaderRoute: typeof AppMenusRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/kioskEditor': {
      id: '/app/kioskEditor'
      path: '/kioskEditor'
      fullPath: '/app/kioskEditor'
      preLoaderRoute: typeof AppKioskEditorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/employees': {
      id: '/app/employees'
      path: '/employees'
      fullPath: '/app/employees'
      preLoaderRoute: typeof AppEmployeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/devices': {
      id: '/app/devices'
      path: '/devices'
      fullPath: '/app/devices'
      preLoaderRoute: typeof AppDevicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/counters': {
      id: '/app/counters'
      path: '/counters'
      fullPath: '/app/counters'
      preLoaderRoute: typeof AppCountersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/companies': {
      id: '/app/companies'
      path: '/companies'
      fullPath: '/app/companies'
      preLoaderRoute: typeof AppCompaniesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/branches': {
      id: '/app/branches'
      path: '/branches'
      fullPath: '/app/branches'
      preLoaderRoute: typeof AppBranchesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit': {
      id: '/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAuditRoute: typeof AppAuditRoute
  AppBranchesRoute: typeof AppBranchesRoute
  AppCompaniesRoute: typeof AppCompaniesRoute
  AppCountersRoute: typeof AppCountersRoute
  AppDevicesRoute: typeof AppDevicesRoute
  AppEmployeesRoute: typeof AppEmployeesRoute
  AppKioskEditorRoute: typeof AppKioskEditorRoute
  AppMenusRoute: typeof AppMenusRoute
  AppOrdersRoute: typeof AppOrdersRoute
  AppPagesRoute: typeof AppPagesRoute
  AppQueuesRoute: typeof AppQueuesRoute
  AppServicesRoute: typeof AppServicesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTicketsRoute: typeof AppTicketsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAuditRoute: AppAuditRoute,
  AppBranchesRoute: AppBranchesRoute,
  AppCompaniesRoute: AppCompaniesRoute,
  AppCountersRoute: AppCountersRoute,
  AppDevicesRoute: AppDevicesRoute,
  AppEmployeesRoute: AppEmployeesRoute,
  AppKioskEditorRoute: AppKioskEditorRoute,
  AppMenusRoute: AppMenusRoute,
  AppOrdersRoute: AppOrdersRoute,
  AppPagesRoute: AppPagesRoute,
  AppQueuesRoute: AppQueuesRoute,
  AppServicesRoute: AppServicesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTicketsRoute: AppTicketsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CustomerRoute: CustomerRoute,
  DisplayRoute: DisplayRoute,
  KioskRoute: KioskRoute,
  LoginRoute: LoginRoute,
  OperatorRoute: OperatorRoute,
  PairRoute: PairRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
